### ISSUE TITLE
On first day of month button to download data from current month should be disabled

### ISSUE THREAD

**Issue by ziutus** [CloudPouch/CloudPouch.dev#4]
On first day of month button to download data from current month should be disabled as there are no data for current month. It should automatically download data for last month as typically you want to check bill for last month..

**Comment by serverlesspolska** [comment]
Hi @ziutus, I have redesigned that a bit in version 1.5.0.

Clicking on the 'Fetch data' button on the first day of a month download data for a whole previous month. It is not disabled because of the following use case:
1. User uses app on 16th of the month. He has data from 1st to 15th of that month.
2. For two weeks, user is not using CloudPouch application
3. User starts application on the first day of the next month
4. User clicks 'Fetch data' to download data of the previous month.

If the button was disabled, the user would not be allowed to get newer data.

**Comment by serverlesspolska** [comment]
On the first of the month app would download full previous month
